---
name: Pull request verification

on:
  pull_request:
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

# Cancel in-progress PR verification workflows. We only care about verifying the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  bugzilla_check:
    name: bugzilla reference check
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Mask secrets
        shell: bash
        run: |
          echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install packages
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y python3 python3-pip python3-requests

      - name: Install python dependencies
        run: pip install python-bugzilla

      - name: Run bugzilla reference check
        run: ./.github/scripts/bugzilla_reference_check.py
        env:
          GITHUB_TOKEN_PSW: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

  checkstyle:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext jss

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyle

  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext jss

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test coverage

      - name: Archive reports
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_reports
          path: |
            **/build/test-results/**/*.xml
            **/build/jacoco/test.exec

  validate_translations:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext jss

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run validate translation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: validate_translation

  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
